# Non standard yml, to be parsed with https://github.com/mkaranasou/pyaml_env
# Paths
data_dir: !ENV ${HOME}/data/Memento
output_dir: output
bids_dir: "/georges/memento/BIDS"
statresults: !ENV ${HOME}/data/Memento/output/statresults
connectivity_matrices: connectivity
custom_atlases : !ENV ${HOME}/data/Memento/atlas
parcellations : !ENV ${HOME}/data/Memento/output/parcellations

# Constants
seed: 1234
alpha: 0.05